Ignored `Layout/IndentArray` and `Layout/IndentHash`
These cop are renamed since rubocop v0.68.0

c.f. https://github.com/rubocop-hq/rubocop/commit/184c2a1e92caa6914fe75a0bcc484c64ab834594

```bash
$ bundle exec rubocop -P
Error: The `Layout/IndentArray` cop has been renamed to `Layout/IndentFirstArrayElement`.
(obsolete configuration found in vendor/bundle/ruby/2.6.0/gems/onkcop-0.53.0.3/config/rubocop.yml, please update it)
The `Layout/IndentHash` cop has been renamed to `Layout/IndentFirstHashElement`.
(obsolete configuration found in vendor/bundle/ruby/2.6.0/gems/onkcop-0.53.0.3/config/rubocop.yml, please update it)
```