Ignored `Layout/IndentationConsistency`
`EnforcedStyle: rails` is renamed to `EnforcedStyle: indented_internal_methods` since rubocop v0.72.0

```
$ bundle exec rubocop -P
Error: obsolete `EnforcedStyle: rails` (for Layout/IndentationConsistency) found in vendor/bundle/ruby/2.6.0/bundler/gems/onkcop-6256494c1f86/config/rubocop.yml
`EnforcedStyle: rails` has been renamed to `EnforcedStyle: indented_internal_methods`
```

c.f. https://github.com/rubocop-hq/rubocop/pull/7163