Workaround for CI
travis build fails when `install.bunler` with cache.

fail:

```
$ ruby --version
ruby 2.6.0dev (2018-03-07 trunk 62693) [x86_64-linux]
$ rvm --version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 1.16.1
$ gem --version
2.7.6

# install.bundler
$ bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
(snip)
Bundle complete! 4 Gemfile dependencies, 18 gems now installed.
Bundled gems are installed into `./vendor/bundle`

$ bundle exec rake
bundler: failed to load command: rake (/home/travis/build/onk/onkcop/vendor/bundle/ruby/2.6.0/bin/rake)
LoadError: cannot load such file -- bundler/dep_proxy
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:888:in `block (2 levels) in expand_dependencies'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `each'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `block in expand_dependencies'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `each'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:874:in `expand_dependencies'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:806:in `converge_locked_specs'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:247:in `resolve'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/setup.rb:10:in `<top (required)>'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```

ok:

```
$ export BUNDLE_GEMFILE=$PWD/Gemfile
$ ruby --version
ruby 2.6.0dev (2018-03-07 trunk 62693) [x86_64-linux]
$ rvm --version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 1.16.1
$ gem --version
2.7.6

# install.bundler
$ bundle install --jobs=3 --retry=3
(snip)
Bundle complete! 4 Gemfile dependencies, 18 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ bundle exec rake
(snip)

Finished in 0.01082 seconds (files took 0.14575 seconds to load)
3 examples, 0 failures
```