Ignored Style/YodaCondition
`equality_operators_only` is changed to `forbid_for_equality_operators_only` since rubocop 0.63.0

```
$ bundle exec rubocop
Error: invalid EnforcedStyle 'equality_operators_only' for Style/YodaCondition found in vendor/bundle/ruby/2.6.0/gems/onkcop-0.53.0.2/config/rubocop.yml
Valid choices are: forbid_for_all_comparison_operators, forbid_for_equality_operators_only, require_for_all_comparison_operators, require_for_equality_operators_only
```